# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_collector_pb2 as data__collector__pb2


class DataCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterInterest = channel.unary_unary(
                '/datacollector.DataCollector/RegisterInterest',
                request_serializer=data__collector__pb2.InterestRequest.SerializeToString,
                response_deserializer=data__collector__pb2.Status.FromString,
                )
        self.GetHistoricalData = channel.unary_unary(
                '/datacollector.DataCollector/GetHistoricalData',
                request_serializer=data__collector__pb2.InterestRequest.SerializeToString,
                response_deserializer=data__collector__pb2.HistoricalDataResponse.FromString,
                )
        self.GetStatistics = channel.unary_unary(
                '/datacollector.DataCollector/GetStatistics',
                request_serializer=data__collector__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=data__collector__pb2.StatisticsResponse.FromString,
                )


class DataCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterInterest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterInterest': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterInterest,
                    request_deserializer=data__collector__pb2.InterestRequest.FromString,
                    response_serializer=data__collector__pb2.Status.SerializeToString,
            ),
            'GetHistoricalData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalData,
                    request_deserializer=data__collector__pb2.InterestRequest.FromString,
                    response_serializer=data__collector__pb2.HistoricalDataResponse.SerializeToString,
            ),
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=data__collector__pb2.StatisticsRequest.FromString,
                    response_serializer=data__collector__pb2.StatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datacollector.DataCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterInterest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datacollector.DataCollector/RegisterInterest',
            data__collector__pb2.InterestRequest.SerializeToString,
            data__collector__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHistoricalData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datacollector.DataCollector/GetHistoricalData',
            data__collector__pb2.InterestRequest.SerializeToString,
            data__collector__pb2.HistoricalDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datacollector.DataCollector/GetStatistics',
            data__collector__pb2.StatisticsRequest.SerializeToString,
            data__collector__pb2.StatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
