# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_collector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_collector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta_collector.proto\x12\rdatacollector\"\x1f\n\x0eUserIdentifier\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"%\n\x06Status\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x0fInterestRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x14\n\x0c\x61irport_icao\x18\x02 \x03(\t\"\x91\x01\n\nFlightInfo\x12\x0e\n\x06icao24\x18\x01 \x01(\t\x12\x12\n\nfirst_seen\x18\x02 \x01(\x03\x12\x11\n\tlast_seen\x18\x03 \x01(\x03\x12\x10\n\x08\x63\x61llsign\x18\x04 \x01(\t\x12\x1d\n\x15\x65st_departure_airport\x18\x05 \x01(\t\x12\x1b\n\x13\x65st_arrival_airport\x18\x06 \x01(\t\"f\n\x16HistoricalDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x07\x66lights\x18\x03 \x03(\x0b\x32\x19.datacollector.FlightInfo2\xb6\x01\n\rDataCollector\x12I\n\x10RegisterInterest\x12\x1e.datacollector.InterestRequest\x1a\x15.datacollector.Status\x12Z\n\x11GetHistoricalData\x12\x1e.datacollector.InterestRequest\x1a%.datacollector.HistoricalDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_collector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERIDENTIFIER']._serialized_start=39
  _globals['_USERIDENTIFIER']._serialized_end=70
  _globals['_STATUS']._serialized_start=72
  _globals['_STATUS']._serialized_end=109
  _globals['_INTERESTREQUEST']._serialized_start=111
  _globals['_INTERESTREQUEST']._serialized_end=170
  _globals['_FLIGHTINFO']._serialized_start=173
  _globals['_FLIGHTINFO']._serialized_end=318
  _globals['_HISTORICALDATARESPONSE']._serialized_start=320
  _globals['_HISTORICALDATARESPONSE']._serialized_end=422
  _globals['_DATACOLLECTOR']._serialized_start=425
  _globals['_DATACOLLECTOR']._serialized_end=607
# @@protoc_insertion_point(module_scope)
