version: '3.8'

networks:
  service_net:
    driver: bridge
  user_db_net:
    driver: bridge
    internal: true 
  data_db_net:
    driver: bridge
    internal: true

    

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - service_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - service_net

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      USER_MANAGER_ADDRESS: user_manager:${UM_PORT}
      DATA_COLLECTOR_ADDRESS: data_collector:${DC_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}" 
    networks:
      - service_net
    depends_on:
      user_manager:
        condition: service_started
      data_collector:
        condition: service_started
  db:
    image: postgres:14-alpine 
    container_name: db_user
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - db_user_data:/var/lib/postgresql/data 
    expose: 
      - 5432
    networks:
      - user_db_net 
    healthcheck: 
        test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
        interval: 5s
        timeout: 5s
        retries: 5
  
  user_manager:
    build: 
      context: ./user_manager
      dockerfile: Dockerfile
    container_name: user_manager
    environment:
      DB_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
      LISTEN_PORT: ${UM_PORT}
    ports:
      - "${UM_PORT}:${UM_PORT}"
    networks:
      - user_db_net 
      - service_net 
    depends_on:
      db:
        condition: service_healthy

  db_collector:
    image: postgres:14-alpine
    container_name: collector_db
    environment:
      POSTGRES_USER: collector_user
      POSTGRES_PASSWORD: collector_password
      POSTGRES_DB: collector_db
    volumes:
      - collector_db_data:/var/lib/postgresql/data
    expose:
      - ${DB_PORT}
    networks:
      - data_db_net 
    healthcheck: 
        test: ["CMD-SHELL", "pg_isready -U collector_user -d collector_db"]
        interval: 5s
        timeout: 5s
        retries: 5

  data_collector:
    build:
      context: ./data_collector
      dockerfile: Dockerfile
    container_name: data_collector
    environment:
      DB_HOST: db_collector
      POSTGRES_DB: collector_db
      POSTGRES_USER: collector_user
      POSTGRES_PASSWORD: collector_password
      USER_MANAGER_ADDRESS: user_manager:${UM_PORT}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      LISTEN_PORT: ${DC_PORT}
      MONITOR_INTERVAL: 43200 
      OPENSKY_CREDS_PATH: /app/credentials.json 
    ports:
      - "${DC_PORT}:${DC_PORT}" 
    networks:
      - data_db_net 
      - service_net 
    depends_on:
      user_manager:
        condition: service_started 
      db_collector:
        condition: service_healthy 

volumes:
  db_user_data: {}      
  collector_db_data: {} 