events {
    worker_connections 1024;
}

http {
    upstream um_http {
        server user_manager:5000;
    }

    upstream dc_http {
        server data_collector:5001;
    }

    server {
        listen 80;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        server_name my_apigw.com;

        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

       # 1. RegisterUser
        # POST http://localhost:8080/users/register
        location /users/register {
            proxy_pass http://um_http/register;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. DeleteUser
        # DELETE http://localhost:8080/users/delete?email=...
        location /users/delete {
            proxy_pass http://um_http/delete;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. CheckUserExists (Utile per debug/frontend)
        # GET http://localhost:8080/users/exists?email=...
        location /users/exists {
            proxy_pass http://um_http/exists;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. RegisterInterest
        # POST http://localhost:8080/collector/interests
        location /collector/interests {
            proxy_pass http://dc_http/interests;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 5. GetStatistics
        # GET http://localhost:8080/collector/statistics?user_email=...&airport_icao=...&days=...
        location /collector/statistics {
            proxy_pass http://dc_http/statistics;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 6. GetHistoricalData
        # GET http://localhost:8080/collector/history?user_email=...&airport_icao=...&request_type=...
        location /collector/history {
            proxy_pass http://dc_http/history;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}