# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_collector.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta_collector.proto\x12\rdatacollector\"K\n\x11StatisticsRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x14\n\x0c\x61irport_icao\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x03 \x01(\x05\"d\n\x12StatisticsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61vg_arrivals\x18\x03 \x01(\x02\x12\x16\n\x0e\x61vg_departures\x18\x04 \x01(\x02\"\x1f\n\x0eUserIdentifier\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"%\n\x06Status\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x97\x01\n\x0fInterestRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x14\n\x0c\x61irport_icao\x18\x02 \x03(\t\x12\x33\n\x0crequest_type\x18\x03 \x01(\x0e\x32\x1d.datacollector.FlightDataType\x12\x12\n\nhigh_value\x18\x04 \x01(\x05\x12\x11\n\tlow_value\x18\x05 \x01(\x05\"\x91\x01\n\nFlightInfo\x12\x0e\n\x06icao24\x18\x01 \x01(\t\x12\x12\n\nfirst_seen\x18\x02 \x01(\x03\x12\x11\n\tlast_seen\x18\x03 \x01(\x03\x12\x10\n\x08\x63\x61llsign\x18\x04 \x01(\t\x12\x1d\n\x15\x65st_departure_airport\x18\x05 \x01(\t\x12\x1b\n\x13\x65st_arrival_airport\x18\x06 \x01(\t\"f\n\x16HistoricalDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x07\x66lights\x18\x03 \x03(\x0b\x32\x19.datacollector.FlightInfo*5\n\x0e\x46lightDataType\x12\x07\n\x03\x41LL\x10\x00\x12\x0b\n\x07\x41RRIVAL\x10\x01\x12\r\n\tDEPARTURE\x10\x02\x32\x8c\x02\n\rDataCollector\x12I\n\x10RegisterInterest\x12\x1e.datacollector.InterestRequest\x1a\x15.datacollector.Status\x12Z\n\x11GetHistoricalData\x12\x1e.datacollector.InterestRequest\x1a%.datacollector.HistoricalDataResponse\x12T\n\rGetStatistics\x12 .datacollector.StatisticsRequest\x1a!.datacollector.StatisticsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_collector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FLIGHTDATATYPE']._serialized_start=696
  _globals['_FLIGHTDATATYPE']._serialized_end=749
  _globals['_STATISTICSREQUEST']._serialized_start=39
  _globals['_STATISTICSREQUEST']._serialized_end=114
  _globals['_STATISTICSRESPONSE']._serialized_start=116
  _globals['_STATISTICSRESPONSE']._serialized_end=216
  _globals['_USERIDENTIFIER']._serialized_start=218
  _globals['_USERIDENTIFIER']._serialized_end=249
  _globals['_STATUS']._serialized_start=251
  _globals['_STATUS']._serialized_end=288
  _globals['_INTERESTREQUEST']._serialized_start=291
  _globals['_INTERESTREQUEST']._serialized_end=442
  _globals['_FLIGHTINFO']._serialized_start=445
  _globals['_FLIGHTINFO']._serialized_end=590
  _globals['_HISTORICALDATARESPONSE']._serialized_start=592
  _globals['_HISTORICALDATARESPONSE']._serialized_end=694
  _globals['_DATACOLLECTOR']._serialized_start=752
  _globals['_DATACOLLECTOR']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
