apiVersion: v1
kind: Service
metadata:
  name: user-manager
spec:
  selector:
    app: user-manager
  ports:
    - name: http
      port: 5050      
      targetPort: 5050
    - name: grpc
      port: 50051      
      targetPort: 50051
    - name: metrics
      port: 8000      
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
        role: monitored-service 
    spec:
      containers:
      - name: user-manager
        image: user-manager:latest 
        command: ["python", "server.py"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        - containerPort: 8000
        env:
        - name: NODE_NAME 
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
  
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name : HTTP_PORT
          value: "5050"
        - name : GRPC_PORT
          value: "50051"

        - name: USER_DB_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@user-db:5432/$(DB_USER)"