apiVersion: v1
kind: Service
metadata:
  name: data-collector
spec:
  selector:
    app: data-collector
  ports:
    - name: http
      port: 5001
      targetPort: 5001
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: metrics
      port: 8000
      targetPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
        role: monitored-service
    spec:
      containers:
      - name: data-collector
        image: data-collector:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent

        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Generazione credentials.json..."
            echo "{\"clientId\": \"$OPENSKY_USER\", \"clientSecret\": \"$OPENSKY_PASS\"}" > credentials.json
            echo "Avvio Data Collector..."
            python server.py

        ports:
        - containerPort: 5001
        - containerPort: 50052
        - containerPort: 8000

        env:
        - name: HTTP_LISTEN_PORT
          value: "5001"
        - name: LISTEN_PORT
          value: "50052"
        
        - name: NODE_NAME 
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        - name: DB_HOST
          value: "data-db"

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
          
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        
        - name: POSTGRES_DB
          value: "flights_db"
        
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        
        - name: USER_MANAGER_ADDRESS
          value: "user-manager:50051"
        
        - name: OPENSKY_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENSKY_USER
        - name: OPENSKY_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENSKY_PASS