syntax= "proto3";

package usermanager;


message UserData {
  string request_id = 1;
  string email = 2;
  string name = 3;
  string surname = 4;
}
  
  message UserIdentifier {
    string email = 1;
  }
  
  message Status {
    bool ok = 1;
    string message = 2;
  }
  
  message UserExistsResponse {
    bool exists = 1;
}

service UserManager {
    rpc RegisterUser(UserData) returns (Status);
    rpc DeleteUser(UserIdentifier) returns (Status);
    rpc CheckUserExists(UserIdentifier) returns (UserExistsResponse);
}